[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildCommand = ""
watchPatterns = ["**/*"]

[deploy]
startCommand = "python backend/app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

